# 本地开发环境配置
spring:
  datasource:
    url: jdbc:mysql://10.10.20.200:3306/api-hu?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: user_dev
    password: Lt@888888
    driver-class-name: com.mysql.cj.jdbc.Driver