server:
  port: 9090

# 本地开发环境配置
spring:
  datasource:
    url: jdbc:mysql://10.10.20.200:3306/api-hu?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: user_dev
    password: Lt@888888
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis打印sql(配合MyBatis Log Plugin插件可以在控制台查看格式化并且填充了占位符的SQL语句)
mybatis:
  config-location:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# log configuration
logging:
  file:
    name: logs/api-hu.log
  level:
    com:
    keqi: debug


